### PR TITLE
Use correct import paths for protobuf packages

### LINKED ISSUE #2095: Failed Proto Imports - Python gRPC
When generating the Python interface as specified in the documentation as follows:

```
python -m grpc_tools.protoc -I./api --python_out=. --grpc_python_out=. api/gobgp.proto api/attribute.proto api/capability.proto
```

I received errors about not being able to find the imports out of the 'gobgp.proto' file, like this:

>gobgp.proto: Import "any/any.proto" was not found or had errors.
>gobgp.proto: Import "empty/empty.proto" was not found or had errors.
>gobgp.proto: Import "timestamp/timestamp.proto" was not found or had errors.

I was able to fix this by modifying the references as follows in the api/*.proto files.

From this:
```
import "any/any.proto";
import "empty/empty.proto";
import "timestamp/timestamp.proto";
```

To this:
```
import "google/protobuf/any.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
```

I don't know if this is an issue with my Python library location (user-based) or if it is just a general Python thing.  If the fix would work for everything I can submit a PR.

### PR DESCRIPTION
**Pull request by ecbaldwin**
The packages `any`, `empty`, and `timestamp` ship with protoc so there
is no need to pull them out of the go package. This simplifies the
generation script and also corrects the import paths for the standard
protobuf types.

Fixes: #2095

### CODE REVIEW

File: tools/grpc/genproto.sh [hunk 1]
```diff
@@ -1,9 +1,10 @@
-#!/usr/bin/env bash -x
```
Comment (ecbaldwin) [inline tools/grpc/genproto.sh]: I removed the `-x` from here and moved it below because this script wouldn't run for me otherwise. I got this: 

```
$ ./tools/grpc/genproto.sh
/usr/bin/env: ‘bash -x’: No such file or directory
```

It is because the shebang line only allows a single argument after the executable. It interpreted `bash -x` as the argument to `env` and `env` couldn't find an executable by that name.

File: tools/grpc/genproto.sh [hunk 2]
```diff
@@ -26,9 +27,7 @@ for pkg in ${INSTALL_PKGS}; do
 done
 
 GOBGP="${PWD}"
-GOPROTO="$(GO111MODULE=on go list -f '{{ .Dir }}' -m github.com/golang/protobuf)"
 
 echo "generating code"
-protoc -I "${GOPROTO}"/ptypes \
```
Comment (ecbaldwin) [inline tools/grpc/genproto.sh]: There is no need to add this import path since these types ship with the protoc compiler under their proper include paths (google/protobuf). So, removing it.

**Comment by fujita** [comment]
I thought that this breaks the compatibility so I need to postpone it until v3. But it seems that it doesn't. Pushed, thanks a lot!
