### PR TITLE
packet/bgp: fix handling of IPv4 mapped IPv6 prefixes

### LINKED ISSUE #1117: 6PE: nil pointer dereference upon "Peer Up"
Hi guys,

Today I updated gobgp, in order to use this new feature `https://github.com/osrg/gobgp/issues/1086`

Unfortunately, when the session gets established a runtime error occurs. More specifically:
```
{"level":"info","msg":"gobgpd started","time":"2016-09-27T10:38:34+02:00"}
{"Topic":"Config","level":"info","msg":"Finished reading the config file","time":"2016-09-27T10:38:34+02:00"}
{"level":"info","msg":"Peer x.x.x.x is added","time":"2016-09-27T10:38:34+02:00"}
{"Topic":"Peer","level":"info","msg":"Add a peer configuration for:x.x.x.x","time":"2016-09-27T10:38:34+02:00"}

{"Key":"x.x.x.x","State":"BGP_FSM_OPENCONFIRM","Topic":"Peer","level":"info","msg":"Peer Up","time":"2016-09-27T10:38:53+02:00"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x74aa62]

goroutine 22 [running]:
panic(0xd6dd80, 0xc820012140)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/osrg/gobgp/table.CidrToRadixkey(0xc8201ebe40, 0x11, 0x0, 0x0)
	/home/app/netops/gobgp/src/github.com/osrg/gobgp/table/destination.go:62 +0xb2
github.com/osrg/gobgp/table.NewDestination(0x7ff40d5915e0, 0xc82023ac80, 0x0, 0x0, 0x0, 0x0)
	/home/app/netops/gobgp/src/github.com/osrg/gobgp/table/destination.go:138 +0x259
github.com/osrg/gobgp/table.(*Table).getOrCreateDest(0xc8202a4d10, 0x7ff40d5915e0, 0xc82023ac80, 0x4111e7)
	/home/app/netops/gobgp/src/github.com/osrg/gobgp/table/table.go:220 +0x2b4
github.com/osrg/gobgp/table.(*Table).insert(0xc8202a4d10, 0xc8202cacc0, 0x20004)
	/home/app/netops/gobgp/src/github.com/osrg/gobgp/table/table.go:72 +0x69
github.com/osrg/gobgp/table.(*TableManager).ProcessPaths(0xc8201ed080, 0xc820132cd8, 0x1, 0x1, 0xc8201243c0, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/home/app/netops/gobgp/src/github.com/osrg/gobgp/table/table_manager.go:272 +0x252
github.com/osrg/gobgp/server.(*BgpServer).propagateUpdate(0xc8201ac400, 0xc8201b9720, 0xc8201243c0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/app/netops/gobgp/src/github.com/osrg/gobgp/server/server.go:571 +0x16ec
github.com/osrg/gobgp/server.(*BgpServer).handleFSMMessage(0xc8201ac400, 0xc8201b9720, 0xc820222980)
	/home/app/netops/gobgp/src/github.com/osrg/gobgp/server/server.go:749 +0x1dbb
github.com/osrg/gobgp/server.(*BgpServer).Serve.func1(0xc820222980)
	/home/app/netops/gobgp/src/github.com/osrg/gobgp/server/server.go:162 +0x49d
github.com/osrg/gobgp/server.(*BgpServer).Serve(0xc8201ac400)
	/home/app/netops/gobgp/src/github.com/osrg/gobgp/server/server.go:246 +0x442
created by main.main
	/home/app/netops/gobgp/src/github.com/osrg/gobgp/gobgpd/main.go:180 +0xbcd
```

It occurs every time that am establishing the session. Could you please advise ?

### PR DESCRIPTION
**Pull request by ishidawataru**
closes #1117

Signed-off-by: Wataru Ishida <ishida.wataru@lab.ntt.co.jp>

### CODE REVIEW

File: packet/bgp/bgp.go [hunk 1]
```diff
@@ -833,6 +833,19 @@ func NewIPAddrPrefix(length uint8, prefix string) *IPAddrPrefix {
 	}
 }
 
+func isIPv4MappedIPv6(ip net.IP) bool {
```
Comment (fujita) [inline packet/bgp/bgp.go]: Simply, `if len(ip) == net.IPv6len && ip.To4() != nil` doesn't work?
